name: CI/CD-PetLandWeb

on:
  push:
    branches:
      - main
      - develop
      - PL-205-advert-service

jobs:
  sending_message:
    name: Sending message
    runs-on: ubuntu-20.04
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Sending telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID}}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN}}
          message: |
            New commit from ${{ github.actor }} on branch ${{ steps.branch-name.outputs.current_branch }}.  
              
            Commit message: ${{ github.event.commits[0].message }}  
              
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
  build:
    name: Build and push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push prod image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "REACT_APP_API_URL=petland-dev-backend.underbeers.space"
            "REACT_APP_CHAT_API_URL=petland-dev-chat-backend.underbeers.space"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pl_frontend:v4

      - name: Send status
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.workflow }}: Publish updated image ${{ job.status }}
        env:
          status: ${{job.status}}

  send_result:
    if: ${{ always() }}
    name: Send result
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - name: Sending telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID}}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN}}
          message: |
            ${{ github.workflow }} ended
